name: Integrate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.4, 8.3, 8.2, 8.1, 8.0]
        laravel: ["11.*", "10.*", "9.*"]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11
            testbench: "^9.0"
          - laravel: 10
            testbench: "^8.31"
          - laravel: 9
            testbench: "^7.50"
        exclude:
          - laravel: "11.*"
            php: 8.1
          - laravel: "11.*"
            php: 8.0
          - laravel: "10.*"
            php: 8.4
          - laravel: "10.*"
            php: 8.0
          - laravel: "9.*"
            php: 8.4
          - laravel: "9.*"
            php: 8.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Override Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}"
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Run tests
        run: vendor/bin/phpunit
